# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 23:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0001_initial'),
        ('games', '0002_auto_20171120_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='amount_batteries',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='lit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basics.Lit'),
        ),
        migrations.AddField(
            model_name='game',
            name='serial_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basics.SerialNumber'),
        ),
    ]
