# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 20:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='tipe',
            new_name='type',
        ),
    ]
