# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0002_auto_20171123_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serialnumber',
            name='name',
            field=models.CharField(max_length=5),
        ),
    ]
