# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 16:58
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0003_auto_20171215_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serialnumber',
            name='name',
            field=models.CharField(max_length=5, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
