# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 15:34
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MorseCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('losses', models.IntegerField(default=0, editable=False)),
                ('won', models.IntegerField(default=0, editable=False)),
                ('difficulty', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('correct_word', models.CharField(max_length=10)),
                ('correct_frequency', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('losses', models.IntegerField(default=0, editable=False)),
                ('won', models.IntegerField(default=0, editable=False)),
                ('difficulty', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('correct_password', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SimonSays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('losses', models.IntegerField(default=0, editable=False)),
                ('won', models.IntegerField(default=0, editable=False)),
                ('difficulty', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('serial_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basics.SerialNumber')),
                ('to_flash', models.ManyToManyField(to='basics.Color')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TheButton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('losses', models.IntegerField(default=0, editable=False)),
                ('won', models.IntegerField(default=0, editable=False)),
                ('difficulty', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('text', models.CharField(max_length=10)),
                ('amount_batteries', models.IntegerField(default=0)),
                ('button_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thebutton_button_color', to='basics.Color')),
                ('strip_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thebutton_strip_color', to='basics.Color')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Wires',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('losses', models.IntegerField(default=0, editable=False)),
                ('won', models.IntegerField(default=0, editable=False)),
                ('difficulty', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('wires', models.ManyToManyField(to='basics.Color')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
