# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 17:11
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_auto_20171120_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='amount_batteries',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='game',
            name='strikes',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)]),
        ),
    ]
